### ISSUE TITLE
Collaboration with SzenarienDB

### ISSUE THREAD

**Issue by Ludee** [IAMconsortium/units#3]
We are currently developing similar functionalities.
Currently, conversion factors are stored in tables, e.g. https://openenergy-platform.org/dataedit/view/model_draft/szenariendb_conversion
The idea is to map the concepts in the [OEO ontology](https://github.com/OpenEnergyPlatform/ontology).

**Comment by danielhuppmann** [comment]
thanks @Ludee for the reference! for our use case (common across message_ix, pyam, etc.), though, most of the factors in the list will be handled by `pint` all by itself.

Also, our climate-modelling colleagues may have some quibbles about using these particular GHG conversion factors, because they depend on the assumed duration of the global warming potential and the latest update (usually IPCC release). Additional context like "GWP-100 AR4" might be useful.

(sorry, I wasn't sure where in your family of tools to make that comment, so I abused this repo).

**Comment by khaeru** [comment]
> our climate-modelling colleagues may have some quibbles

per the above, see IAMconsortium/pyam#340 and IAMconsortium/pyam#341 for some ideas about handling different GWPs.

@Ludee I'm very happy for this repo to be integrated with others. The main requirement is that this repo contains a text file (currently definitions.txt) that is ready-to-use with Pint. Anything more elaborate is welcome, so long as (a) that file exists, (b) in a predictable location, and (c) it doesn't increase the maintenance overhead.

So, for instance:
- If you wanted to set up some scripts to ensure your OEO repo is in sync with this one, please go ahead. We might add a link in the README; please open a PR.
- The pyam issues linked above contain the suggestion from @gidden that this become an installable Python package. I'm not opposed, but:
  - It should be packaged according to best practices, and
  - I won't personally volunteer to set up and maintain the packaging, since it's not necessary for the primary use-case.
